### ISSUE TITLE
Well done!! License?

### ISSUE THREAD

**Issue by DefinitelyMaybe** [ErdongChen-Andrew/CharacterControl#1]
Hey there!

saw this on twitter! Happy to see the source make it to public :)

I'd like to convert this into something we could use over in [threlte](https://threlte-next-docs.vercel.app/) but I don't want to start on that unless your ok with it?

**Comment by ErdongChen-Andrew** [comment]
Hey there!

Thank you for reaching out! I'm glad you're interested in the source code.
I have just added the MIT license to the project. Feel free to convert and adapt it for your purposes at threlte. 
If you have any further questions or need any assistance, please don't hesitate to let me know :)

**Comment by DefinitelyMaybe** [comment]
thank you so much!
