### ISSUE TITLE
Example folder does not work, and no repo for working example

### ISSUE THREAD

**Issue by Seanmclem** [ErdongChen-Andrew/CharacterControl#10]
The [example folder in the repo](https://github.com/pmndrs/ecctrl/tree/main/example), has some paths that don't resolve properly, and doesn't have a package.json, so you can't really run it anymore. 
Also, [this example](https://character-control.vercel.app/) doesn't seem to have a repository to look at.

**Comment by ErdongChen-Andrew** [comment]
To run the example app, you'll need to clone the entire repository since the package.json is located outside the example folder. Follow these steps, and you should be able to run the playground example: 
```js
// Install dependencies (only the first time)
npm install

// Run the local server at localhost:5173
npm run dev

// Build for production in the example/exampleDist/ directory
vite build -c vercelVite.config.js
```

**Comment by Seanmclem** [comment]
Thanks, I thought I tried that but definitely not. Pretty unrelated, but I do have one more question. Any idea why my reimplementation of that exact scene in [this codesandbox](https://codesandbox.io/p/github/Seanmclem/game-stuff-2/main) turns out so much darker and such?

from [this repo](https://github.com/Seanmclem/game-stuff-2).

**Comment by Seanmclem** [comment]
like this 
<img width="932" alt="Screen Shot 2023-11-25 at 5 42 57 PM" src="https://github.com/ErdongChen-Andrew/CharacterControl/assets/6831540/9a547db6-284e-4aa8-ba9e-ef82da9d6b8f">

**Comment by ErdongChen-Andrew** [comment]
Try with different versions of three and r3f. I encountered a similar issue with the latest version of threejs. This won't affect the controller's functionality
