### ISSUE TITLE
Added first person view ?

### ISSUE THREAD

**Issue by rIcard0-sro** [ErdongChen-Andrew/CharacterControl#2]
Do you think it would be easy to set up a first-person view of the character?

start in the 3rd person and when you scroll with the mouse with a transition would arrive in the first person and the same for the reverse.

Great for your work, well done!

**Comment by ErdongChen-Andrew** [comment]
> 

Thank you for your feedback! The zoom in/out feature was initially added to the project, but it didn't function as smoothly as I had anticipated. Once I figure out the correct approach, I will incorporate the first-person view.

**Comment by ErdongChen-Andrew** [comment]
Hi @ricardo-eth , the first person view is not build in with the controller, but you can enable it by changing the settings like this: &lt;Ecctrl camMinDis={-0.001} camFollowMult={100}>

**Comment by dachieu2k2** [comment]
I think you mean ```camInitDis={-0.001}``` 😅

**Comment by ErdongChen-Andrew** [comment]
@dachieu2k2 setting both 'camInitDis' and 'camMinDis' to -0.001 will ensure that the camera is initially in a first-person view 😁. The 'camMinDis={-0.001}' is essential as it defines the closest point the camera can reach when zooming in.
