### ISSUE TITLE
Mobile joystick

### ISSUE THREAD

**Issue by sliktrik** [ErdongChen-Andrew/CharacterControl#6]
First off this project is amazing 👏

it would be great to see a joystick integrated for touch devices like https://www.cssscript.com/demo/touch-virtual-joystick/

**Comment by ErdongChen-Andrew** [comment]
Will definitely consider adding a joystick in the future update. But first I need to find a proper way to handle camera movement on mobile devices.

**Comment by sliktrik** [comment]
I think this is a good example https://niksgames.com/blockland/

I’ve seen a couple of other projects handle it this way 

as you move the joystick left and right it rotates the player and as you move up down it controls the movement

the whole time the camera is fixed behind the player at a set distance and follows the rotation

**Comment by ErdongChen-Andrew** [comment]
@sliktrik it's now supports touch screen controls 😁

**Comment by sliktrik** [comment]
👏 epic work

**Comment by frault75** [comment]
good job!
