### ISSUE TITLE
auto-balance toggle off 

### ISSUE THREAD

**Issue by abhicominin** [ErdongChen-Andrew/CharacterControl#8]
While toggling off the auto-balance feature the physics bodies associated with hands does not stay at places

**Comment by ErdongChen-Andrew** [comment]
Hmm... I've noticed that issue. I'll fix it in the next update.

**Comment by ErdongChen-Andrew** [comment]
Alright, it should be fixed now. Thanks for pointing this out. Feel free to let me know if you come across any other issues. 👍
